server:
  port: 8080
  servlet:
    context-path: "/ecommerce"

spring:
    datasource:
      url: "jdbc:mysql://localhost:3306/ecommerce"
      username: root
      password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL8Dialect
#          format_sql: true

jwt:
  signerKey: "HbbIaCJHm0Oy1vHiO5Se1VVTFAR3BiGVM7RK/rVE8A3/PfRxu8tBBGyAZRWbR5eB"
  valid-duration: 20 #in seconds
  refreshable-duration: 120 #in seconds

app:
  upload:
    dir: "D:/Java/Products/ecommerce-uploads"

